[package]
name = "data_server"
edition = '2018'
publish = false
version = "0.0.0-alpha.0"

[dependencies]
rocket = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
mocktopus = "0.5"

[patch.crates-io]
mocktopus = { git = "https://github.com/rye/Mocktopus" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "fp-ds"
path = "src/main.rs"
