[package]
name = "data_server"
publish = false
version = "0.0.0-alpha.0"

[dependencies]
git2 = "0.7"
rocket = "0.4"
serde = "1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "fp-ds"
path = "src/main.rs"
