---
x-defs:
  default_docker: &rust_docker [{image: circleci/rust:1.29}]

version: 2
jobs:
  fetch-deps:
    docker: *rust_docker
    steps:
      - run: rustup default nightly
      - checkout
      - run: cargo fetch

  test:
    docker: *rust_docker
    steps:
      - run: rustup default nightly
      - checkout
      - run: cargo test

  rustfmt:
    docker: *rust_docker
    steps:
      - run: rustup default nightly
      - checkout
      - run: rustup component add rustfmt-preview --toolchain nightly
      - run: cargo fmt --all -- --check

  compile:
    docker: *rust_docker
    steps:
      - run: rustup default nightly
      - checkout
      - run: cargo build -j8 --release

workflows:
  version: 2
  general:
    jobs:
      - fetch-deps
      - rustfmt:
          requires: [ fetch-deps ]
      - test:
          requires: [ fetch-deps ]
      - compile:
          requires: [ rustfmt, test ]


# TODO nightly after rust nightlies get published
# e.g. 4am
