---
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - run: rustup default nightly
      - checkout
      - run: cargo build
      - run: cargo test
      - run: rustup component add rustfmt-preview --toolchain nightly
      - run: rustfmt --all -- --check
