---
x-defs:
  default_docker: &rust_docker [{image: "rustlang/rust:nightly"}]

version: 2
jobs:
  fetch-deps:
    docker: *rust_docker
    steps:
      - checkout
      - run: cargo fetch
      - run: cargo build --all
      - save_cache:
          key: ds-v1-docker--{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - "/usr/local/cargo"
            - "./target"

  test:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-{{ epoch }}
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-
      - run: cargo test

  rustfmt:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-{{ epoch }}
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-
      - run: rustup component add rustfmt-preview --toolchain nightly
      - run: cargo fmt --all -- --check

  compile:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-{{ epoch }}
            - ds-v1-docker--{{ arch }}-{{ .Branch }}-
      - run: cargo build -j2 --release

workflows:
  version: 2
  general:
    jobs:
      - fetch-deps
      - rustfmt:
          requires: [ fetch-deps ]
      - test:
          requires: [ fetch-deps ]
      - compile:
          requires: [ fetch-deps, rustfmt, test ]


# TODO nightly after rust nightlies get published
# e.g. 4am
