---
x-defs:
  default_docker: &rust_docker [{image: "rustlang/rust:nightly"}]

version: 2
jobs:
  test:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
            - ds-v1-docker--{{ arch }}-
      - run: cargo fetch
      - run: cargo build
      - save_cache:
          key: ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo"
            - "./target"
      - run: cargo test

  rustfmt:
    docker: *rust_docker
    steps:
      - checkout
      # No need for cache...
      - run: rustup component add rustfmt-preview --toolchain nightly
      - run: cargo fmt --all -- --check

  clippy:
    docker: *rust_docker
    steps:
      - checkout
      # No need for cache...
      - run: rustup component add clippy --toolchain=nightly || cargo install --git ssh://git@github.com/rust-lang/rust-clippy.git --force clippy
      - run: cargo clippy

  compile:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
            - ds-v1-docker--{{ arch }}-
      - run: cargo build

  docker-build:
    docker: [{image: "docker:stable"}]
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-image-{{ .Revision }}
            - ds-v1-docker--{{ arch }}-image
      - run: docker build .
      - run: docker save $(docker images --quiet --all) > /tmp/image.tar
      - save_cache:
          key: ds-v1-docker--{{ arch }}-image-{{ .Revision }}
          paths:
            - /tmp/image.tar

workflows:
  version: 2
  general:
    jobs:
      - rustfmt
      - clippy
      - test
      - compile:
          requires: [ rustfmt, test, clippy ]
      - docker-build:
          requires: [ compile ]


# TODO nightly after rust nightlies get published
# e.g. 4am
