---
x-defs:
  default_docker: &rust_docker [{image: "rustlang/rust:nightly"}]

version: 2
jobs:
  test:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
            - ds-v1-docker--{{ arch }}-
      - run: cargo fetch
      - run: cargo build
      - save_cache:
          key: ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo"
            - "./target"
      - run: cargo test

  rustfmt:
    docker: *rust_docker
    steps:
      - checkout
      # No need for cache...
      - run: rustup component add rustfmt-preview --toolchain nightly
      - run: cargo fmt --all -- --check

  compile:
    docker: *rust_docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - ds-v1-docker--{{ arch }}-{{ checksum "Cargo.lock" }}
            - ds-v1-docker--{{ arch }}-
      - run: cargo build
      - run: cargo build --release

workflows:
  version: 2
  general:
    jobs:
      - rustfmt
      - test
      - compile:
          requires: [ rustfmt, test ]


# TODO nightly after rust nightlies get published
# e.g. 4am
